# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

approximatelyEqualRel <- function(a, b, relEpsilon = 0.0001) {
    .Call('_robbayma_approximatelyEqualRel', PACKAGE = 'robbayma', a, b, relEpsilon)
}

approximatelyEqualAbsRel <- function(a, b, absEpsilon = 0.0001, relEpsilon = 0.0001) {
    .Call('_robbayma_approximatelyEqualAbsRel', PACKAGE = 'robbayma', a, b, absEpsilon, relEpsilon)
}

group_data1 <- function(data, grouping_vec) {
    .Call('_robbayma_group_data1', PACKAGE = 'robbayma', data, grouping_vec)
}

group_data2 <- function(data, grouping_vec) {
    .Call('_robbayma_group_data2', PACKAGE = 'robbayma', data, grouping_vec)
}

substr <- function(Betas, Ig_vec) {
    .Call('_robbayma_substr', PACKAGE = 'robbayma', Betas, Ig_vec)
}

get_design <- function(grouping_vec, n_groups) {
    .Call('_robbayma_get_design', PACKAGE = 'robbayma', grouping_vec, n_groups)
}

matrix_rgamma <- function(n_genes, n_exp, shape, scaling_mat) {
    .Call('_robbayma_matrix_rgamma', PACKAGE = 'robbayma', n_genes, n_exp, shape, scaling_mat)
}

save_iteration_cpp <- function(mcmc_output, model_output, su) {
    .Call('_robbayma_save_iteration_cpp', PACKAGE = 'robbayma', mcmc_output, model_output, su)
}

update_betai_cpp <- function(model_input, model_output) {
    .Call('_robbayma_update_betai_cpp', PACKAGE = 'robbayma', model_input, model_output)
}

update_lambda_cpp <- function(model_input, model_output) {
    .Call('_robbayma_update_lambda_cpp', PACKAGE = 'robbayma', model_input, model_output)
}

update_mhnuphi_cpp <- function(model_input, model_output) {
    .Call('_robbayma_update_mhnuphi_cpp', PACKAGE = 'robbayma', model_input, model_output)
}

update_rjbetai_cpp <- function(data, design, total_mu, n_groups, Betas, phi_scaling, Ig_vec, taue, p, gene_mu_grouped, m_tau, current_gene, lambda) {
    .Call('_robbayma_update_rjbetai_cpp', PACKAGE = 'robbayma', data, design, total_mu, n_groups, Betas, phi_scaling, Ig_vec, taue, p, gene_mu_grouped, m_tau, current_gene, lambda)
}

update_rjnufine_cpp <- function(model_input, model_output) {
    .Call('_robbayma_update_rjnufine_cpp', PACKAGE = 'robbayma', model_input, model_output)
}

update_taue_cpp <- function(model_input, model_output) {
    .Call('_robbayma_update_taue_cpp', PACKAGE = 'robbayma', model_input, model_output)
}

update_wdbetai_cpp <- function(data, design, total_mu, n_groups, Betas, phi_scaling, Ig_vec, taue, current_gene, lambda) {
    .Call('_robbayma_update_wdbetai_cpp', PACKAGE = 'robbayma', data, design, total_mu, n_groups, Betas, phi_scaling, Ig_vec, taue, current_gene, lambda)
}

